Remove empty commit, add clone's sha

diff --git a/scripts/generate-go-project-files b/scripts/generate-go-project-files
--- a/scripts/generate-go-project-files
+++ b/scripts/generate-go-project-files
@@ -49,6 +49,7 @@ main() {
   local files
   local lfiles
   local xfiles
+  local sha
 
   if [[ -n "$(find . -mindepth 1 | cut -c 1)" ]]; then
     printf "%s: Sorry, the current directory contains files\\n" "$0" >&2
@@ -58,34 +59,35 @@ main() {
   printf "Creating project %s from %s\\n" "${PROJECT}" "${BASE_URL}"
 
   git clone --depth 1 --branch master --quiet "${BASE_URL}" .
+  sha="$(git rev-parse --short HEAD)"
 
-  # get list of executable files
+  # get lists of executable files and symlinks
   xfiles=()
-  while IFS= read -r -d $'\0'; do
-    xfiles+=("${REPLY}")
-  done < <(git ls-files --stage -z | grep ^...7 | cut -f 2)
-
-  # get list of symlinks
   lfiles=()
   while IFS= read -r -d $'\0'; do
-    lfiles+=("${REPLY}")
-  done < <(git ls-files --stage -z | grep ^12 | cut -f 2)
+    if grep -q ^...7 <<<"${REPLY}"; then
+      xfiles+=("$(cut -f 2- <<<"${REPLY}")")
+    fi
+    if grep -q ^.2 <<<"${REPLY}"; then
+      lfiles+=("$(cut -f 2- <<<"${REPLY}")")
+    fi
+  done < <(git ls-files --stage -z)
 
   rm -fr .git
+
   files=()
   while IFS= read -r -d $'\0'; do
-    # skip rewriting symlinks as it's unneeded
-    if containsElement "${REPLY}" "${lfiles[@]}"; then
-      continue
+    # don't rewrite symlinks as it's unneeded (and fails on windows)
+    if ! containsElement "${REPLY}" "${lfiles[@]}"; then
+      files+=("${REPLY}")
     fi
-    files+=("${REPLY}")
   done < <(find . \( -type f -o -type l \) -printf "%P\\000")
+
   git init --quiet
-  git commit --allow-empty --quiet --message "Initial (empty) commit"
   git add .
   # restore executable bits if they've been unset
   git update-index --chmod=+x "${xfiles[@]}"
-  git commit --quiet --message "Initial commit (from ${BASE_PROJECT})"
+  git commit --quiet --message "Initial commit (from ${BASE_PROJECT} @ ${sha})"
   sed -i "\
     /##SKIP_REWRITING##/ !{
       s|\\b${BASE_OWNER}\\b|${OWNER}|g;
@@ -94,7 +96,6 @@ main() {
       s|\\b${BASE_PROJECT_NAME}\\b|${PROJECT_NAME}|g; 
     }
    " "${files[@]}"
-
   git commit --all --quiet --message "Change ${BASE_PROJECT} to ${PROJECT}"
   git log --oneline
 }
